@extends('layouts.public')

@section('content')
@include('landing.hero')
@include('landing.fitur')
@include('landing.alur')
@include('landing.untuk-siapa')
@include('landing.tentang')
@include('landing.how-it-works')
@include('landing.timeline')
@include('landing.vacancies')
@include('landing.offer-slider')
@include('landing.testimonials')
<x-partner-marquee/>
@include('landing.gallery')
@include('landing.cta')
@include('landing.faq')
@include('landing.back-to-top')
@endsection